# Generated by Django 5.0.6 on 2024-06-12 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
