# Generated by Django 5.0.6 on 2024-06-12 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycart', '0002_photo_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
